// Bundles content/tasks/<slug>/ into lib/content.generated.ts so task content is
// available at runtime on Cloudflare Workers (which has no filesystem).
//
// Run automatically via the `predev` / `prebuild` npm scripts, or directly:
//   node scripts/build-content.mjs

import { readFileSync, readdirSync, statSync, writeFileSync, existsSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = process.cwd();
const TASKS_DIR = join(ROOT, "content", "tasks");
const OUT = join(ROOT, "lib", "content.generated.ts");

/** Recursively collect text files under `dir` as { path, content }, path relative to `dir`. */
function collectFiles(dir) {
  if (!existsSync(dir)) return [];
  const out = [];
  const walk = (current) => {
    for (const name of readdirSync(current).sort()) {
      const full = join(current, name);
      if (statSync(full).isDirectory()) {
        walk(full);
      } else {
        out.push({
          path: relative(dir, full).split("\\").join("/"),
          content: readFileSync(full, "utf8"),
        });
      }
    }
  };
  walk(dir);
  return out;
}

function readTask(slug) {
  const dir = join(TASKS_DIR, slug);
  const meta = JSON.parse(readFileSync(join(dir, "task.json"), "utf8"));
  const promptPath = join(dir, "prompt.md");
  const rubricPath = join(dir, "rubric.md");
  return {
    slug: meta.slug,
    title: meta.title,
    difficulty: meta.difficulty,
    estimatedMinutes: meta.estimatedMinutes,
    summary: meta.summary,
    entry: meta.entry,
    tags: meta.tags ?? [],
    company: meta.company ?? null,
    prompt: existsSync(promptPath) ? readFileSync(promptPath, "utf8") : "",
    rubric: existsSync(rubricPath) ? readFileSync(rubricPath, "utf8") : "",
    starter: collectFiles(join(dir, "starter")),
    visibleTests: collectFiles(join(dir, "tests_visible")),
    hiddenTests: collectFiles(join(dir, "tests_hidden")),
  };
}

function main() {
  const slugs = existsSync(TASKS_DIR)
    ? readdirSync(TASKS_DIR).filter((n) => statSync(join(TASKS_DIR, n)).isDirectory()).sort()
    : [];

  const tasks = {};
  for (const slug of slugs) {
    const task = readTask(slug);
    if (task.slug !== slug) {
      throw new Error(`Task slug mismatch: folder "${slug}" vs task.json "${task.slug}"`);
    }
    tasks[slug] = task;
  }

  const banner = "// AUTO-GENERATED by scripts/build-content.mjs. Do not edit by hand.\n";
  const types = `
export type TaskFile = { path: string; content: string };

export type GeneratedTask = {
  slug: string;
  title: string;
  difficulty: string;
  estimatedMinutes: number;
  summary: string;
  entry: string;
  tags: string[];
  company: string | null;
  prompt: string;
  rubric: string;
  starter: TaskFile[];
  visibleTests: TaskFile[];
  hiddenTests: TaskFile[];
};
`;
  const body = `\nexport const TASKS: Record<string, GeneratedTask> = ${JSON.stringify(tasks, null, 2)};\n`;

  writeFileSync(OUT, banner + types + body, "utf8");
  console.log(`Wrote ${OUT} with ${slugs.length} task(s): ${slugs.join(", ")}`);
}

main();
